### ISSUE TITLE
请问可以搬运repo到gitee么

### ISSUE THREAD

**Issue by ShenYuhan** [wzwtt/ikun#3]
鉴于网络问题，可能无法从github获取这个repo的表情包，是否可以放一个gitee或者其他国内的代码平台。

**Comment by wzwtt** [comment]
已经有了，内容已使用 [workflows](https://github.com/wzwtt/ikun/blob/master/.github/workflows/sync2gitee.yml) 与 GitHub 完全同步。
https://gitee.com/wzwtt/ikun
感谢您的支持。
